---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app51-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-idp-demo/backstage-sample-quarkus-app51-gitops